# Generated by Django 6.0.4 on 2026-04-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='experiencia',
            name='tipo',
            field=models.CharField(choices=[('trabajo', 'Trabajo'), ('educacion', 'Educación'), ('certificacion', 'Certificación'), ('proyecto', 'Proyecto')], default='trabajo', max_length=20),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='enlace_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='enlace_github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologia',
            field=models.CharField(help_text='Separá varias tecnologías con comas. Ej: Python, Django, PostgreSQL', max_length=120),
        ),
    ]
