# Generated by Django 6.0.4 on 2026-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0003_delete_contacto_alter_experiencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='cargo_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo (EN)'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='descripcion_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción (EN)'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='empresa_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa (EN)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción (EN)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologia_en',
            field=models.CharField(blank=True, help_text='Opcional. Si se deja vacío, se usa la versión en español.', max_length=120, verbose_name='Tecnología (EN)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título (EN)'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo (ES)'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción (ES)'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='empresa',
            field=models.CharField(max_length=100, verbose_name='Empresa (ES)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción (ES)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologia',
            field=models.CharField(help_text='Separá varias tecnologías con comas. Ej: Python, Django, PostgreSQL', max_length=120, verbose_name='Tecnología (ES)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título (ES)'),
        ),
    ]
